apiVersion: v1
kind: Service
metadata:
  name: paymentms
  namespace: condominium
  labels:
    app: paymentms
spec:
  selector:
    app: paymentms
  ports:
    - name: http
      port: 80
      targetPort: 8080
