apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: jarango71/condominiumgw
      context: ../condominiumgw
      jib: {}
    - image: jarango71/managerms
      context: ../managerms
      jib: {}
    - image: jarango71/paymentms
      context: ../paymentms
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
