apiVersion: v1
kind: Service
metadata:
  name: managerms
  namespace: condominium
  labels:
    app: managerms
spec:
  selector:
    app: managerms
  ports:
    - name: http
      port: 80
      targetPort: 8080
