# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  condominiumgw-app:
    image: condominiumgw
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_R2DBC_URL=r2dbc:postgresql://condominiumgw-postgresql:5432/condominiumgw
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://condominiumgw-postgresql:5432/condominiumgw
      - JHIPSTER_SLEEP=60 # gives time for microservices to boot before the gateway, the entire stack will be ready to accept incomming requests.
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  condominiumgw-postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/jhipster/condominiumgw/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=condominiumgw
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
